name: package-test
on:  
  push:    
    branches:      
      - main 
    paths: 
      - 'package-new/**'
env:
  BUILD_ENV: package-new
jobs:  
  publish-gpr:    
    runs-on: ubuntu-latest 
    permissions:
      packages: write
      contents: read   
    steps:      
      - uses: actions/checkout@v2      
      - uses: actions/setup-node@v2        
        with:          
          node-version: 14          
          registry-url: https://npm.pkg.github.com/      
      - name: Install
        working-directory: ${{env.BUILD_ENV}}
        run: npm install
      - name: Build
        working-directory: ${{env.BUILD_ENV}}
        run: npm run build  
      - name: Publish
        working-directory: ${{env.BUILD_ENV}}
        run: npm publish     
    env:
      NODE_AUTH_TOKEN: ${{secrets.TOKEN_SECRET}}